### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by BitBargain** [chemicstry/recksplorer#20]
Thanks for the nice visualizer! I use it every day.

Can we please get a cleanup routine added? During the pre-mainnet dev, it was strongly recommended that we start from scratch and remove all the databases, so the node keys kept changing.

So now there are 4 nodes with the same name and different keys, I haven't used the old ones for over a month and the channels should be closed by now. I imagine the keys won't be changing in the future now that we're closer to stable versions of the node software.

I'd love to see a more accurate, up-to-date version that doesn't contain nodes and channels that haven't been active for very long.

**Comment by chemicstry** [comment]
I did a clean LND installation a few weeks ago and it loaded up all these old nodes again. Probably because other nodes still send announcements about them (or their unclosed channels). I think this is an issue with LND graph pruning which it does not do.
