### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by laanwj** [chemicstry/recksplorer#22]
Would be nice to have a setting to have a dark or black background (all the white hurts my eyes!). This looks quite amazing:

![](https://pbs.twimg.com/media/DbZiydfVMAAsVF9.jpg)
![](https://pbs.twimg.com/media/DbZizOEUwAAxbq2.jpg)
(from https://twitter.com/ArminVanBitcoin/status/988385876274184192 . Currently he manually sets the background to black using browser debug to achieve this.)

**Comment by chemicstry** [comment]
Nice suggestion! Added in 6121dd7b03e1bd41214a099433afafbfc59ecca0. You can now select it on top right corner 👍

**Comment by laanwj** [comment]
Thank you, this is great!
