### ISSUE TITLE
Recommended server specs for recksplorer

### ISSUE THREAD

**Issue by xelawafs** [chemicstry/recksplorer#26]
What are the recommended server specs for recksplorer? While operating recksplorer on a node, I noticed it consumes significantly more resources than both lnd and btcd combined, especially CPU.

It would be great to know what allocation anyone setting up should consider

**Comment by chemicstry** [comment]
It takes a lot of CPU resources to layout graph, but once it finishes, it should drop to zero. On i7-4770 it takes about a minute to do that. If your CPU is slow, it may not keep up with update interval, which is set by the `updateInterval` parameter. On each update whole layout is recalculated.

**Comment by xelawafs** [comment]
This keeps iterating for me:

```
Fetching graph data from lightning daemon...
Successfully fetched 2016 nodes and 6742 edges
Calculating graph layout...
Layout: 0%
Layout: 60%
Layout: 10%
Layout: 70%
Layout: 20%
Layout: 80%
Layout: 30%
Layout: 90%
Layout: 40%
Updated graph data
Layout: 50%
Fetching graph data from lightning daemon...
Successfully fetched 2016 nodes and 6742 edges
Calculating graph layout...
Layout: 0%
Layout: 10%
Layout: 60%
Layout: 20%
Layout: 70%
Layout: 30%
Layout: 80%
Layout: 40%
Layout: 90%
Layout: 50%
Updated graph data
Fetching graph data from lightning daemon...
Successfully fetched 2016 nodes and 6742 edges
Calculating graph layout...
```

**Comment by chemicstry** [comment]
Yes, this is the exact behaviour I described. Increase `updateInterval` setting so that layout is calculated before next update.
