### ISSUE TITLE
Expiring old nodes

### ISSUE THREAD

**Issue by laanwj** [chemicstry/recksplorer#27]
Do old nodes ever expire and disappear from the view?
I had to re-initialize my node at some point, and now it has been listed doubly for almost two months (the old instance without any channels).

**Comment by chemicstry** [comment]
As explained in #20, this is an issue with LND as it does not prune old graph nodes. Maybe it does now, I'm still running quite an old version. I could manually filter nodes by `last_update` field, but I think they can still be useful for historic purposes.

**Comment by laanwj** [comment]
Personally I think this clutters the graph and it would be useful at least as an option.
But ok, closing this if this is already resolved in #20.
