### ISSUE TITLE
What happened to lnmainnet.gaben.win?

### ISSUE THREAD

**Issue by normandmickey** [chemicstry/recksplorer#31]
I'm just curious why lnmainnet.gaben.win is no longer online?

**Comment by chemicstry** [comment]
My lnd node had a power failure which caused channels db to corrupt and I couldn't restore it without much effort. Since multiple other people hosted this software, I decided not to repair it. And with growing LN size this is getting kinda useless.

**Comment by normandmickey** [comment]
IMHO you are wasting a shit-ton of traffic.  I registered recksplorer.com
and was going to take a crack at put it back up.  Would you consider
redirecting your domain?
