### ISSUE TITLE
Number of channels not updating. 

### ISSUE THREAD

**Issue by pedro-roberto** [chemicstry/recksplorer#9]
For the past two days I see the number of channels fixed at 429 and the number of channels fixed at 1007. I think this is very unlikely especially when taking into account that every hour there was a new node before...

**Comment by raindogdance** [comment]
It seems that the address/server has been switched.. This looks like the current one: https://lnmainnet.rompert.com/

**Comment by chemicstry** [comment]
Address has not changed. That address is the same software but ran by a different person.

As for the original website, my LND has frozen/crashed and I was on vacation. I hope to fix this soon. Since this has nothing to do with the explorer software itself, I'm going to close it.
